name: Check Parallel Running

on: [push]

jobs:
  setup:
    runs-on: ubuntu-18.04

  job1:
    needs: ["setup"]
    steps:
      - name: echo hello world string
        run: echo "Hello World!"

  job2:
    needs: ["setup"]
    steps:
      - name: echo hello world Again string
        run: echo "Hello World Again!"
